title: Stackbit Vanilla Theme
baseURL: /
params:
  header:
    type: header
    template: header
    title: Stackbit Vanilla
    has_nav: true
    nav_links:
      - type: action
        template: action
        label: Home
        url: /
      - type: action
        template: action
        label: Generic
        url: /generic/
      - type: action
        template: action
        label: Elements
        url: /elements/
      - type: action
        template: action
        label: Ipsum
        url: /ipsum/
  footer:
    type: footer
    template: footer
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created with
      <a href="https://www.stackbit.com/?utm_source=deployed-footer"
      target="_blank" rel="noopener">Stackbit</a>. Create yours <a
      href="https://app.stackbit.com/create?theme=vanilla&utm_source=deployed-footer"
      target="_blank" rel="noopener">now</a>
    has_social: true
    social_links:
      - type: action
        template: action
        label: Twitter
        url: 'https://twitter.com/'
        new_window: true
      - type: action
        template: action
        label: Instagram
        url: 'https://www.instagram.com/'
        new_window: true
      - type: action
        template: action
        label: GitHub
        url: 'https://github.com/'
        new_window: true
      - type: action
        template: action
        label: LinkedIn
        url: 'https://www.linkedin.com/'
        new_window: true
      - type: action
        template: action
        label: DEV
        url: 'https://dev.to/'
        new_window: true
  domain: 'https://curious-mustard-b5014.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
