---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: https://rob-stackbit.ngrok.io/project/60ab50141ddecfc59119487d/webhook/forestry
sections:
- type: document
  path: config.yaml
  label: Site Configuration
  templates:
  - config
- type: document
  path: data/author.json
  label: Author
  templates:
  - author
- type: directory
  path: content
  label: Pages
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - advanced
  - page
  - post
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.47
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.80.0
